# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    FormerDUTStudentsBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN: ROLE_STUDENT
    #ROLE_ADMIN: [ROLE_STUDENT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class: FormerDUTStudentsBundle\Entity\User
        property: username

  access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/isLogged, role: IS_AUTHENTICATED_ANONYMOUSLY }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: ~
      provider: main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: self
      logout:
        path:       logout
        target:     login


