<?php

namespace Proxies\__CG__\FormerDUTStudentsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \FormerDUTStudentsBundle\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'studentFormations', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'id', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'name', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'creationDate', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'closingDate'];
        }

        return ['__isInitialized__', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'studentFormations', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'id', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'name', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'creationDate', '' . "\0" . 'FormerDUTStudentsBundle\\Entity\\Formation' . "\0" . 'closingDate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate($creationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClosingDate($closingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClosingDate', [$closingDate]);

        return parent::setClosingDate($closingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getClosingDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClosingDate', []);

        return parent::getClosingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addStudent(\FormerDUTStudentsBundle\Entity\Student $student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStudent', [$student]);

        return parent::addStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStudent(\FormerDUTStudentsBundle\Entity\Student $student)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStudent', [$student]);

        return parent::removeStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudents', []);

        return parent::getStudents();
    }

    /**
     * {@inheritDoc}
     */
    public function addStudentFormation(\FormerDUTStudentsBundle\Entity\StudentFormation $studentFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStudentFormation', [$studentFormation]);

        return parent::addStudentFormation($studentFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStudentFormation(\FormerDUTStudentsBundle\Entity\StudentFormation $studentFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStudentFormation', [$studentFormation]);

        return parent::removeStudentFormation($studentFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentFormations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentFormations', []);

        return parent::getStudentFormations();
    }

}
