################################ Route to students methods ######################################

students:
    path:     /students
    defaults:
        _controller: FormerDUTStudentsBundle:Student:getStudents
        _format: json
    methods:  [GET]

student:
    path:     /students/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Student:getStudent
        _format: json
    methods:  [GET]
    requirements:
        id: \d+

add_student:
    path:     /students
    defaults:
        _controller: FormerDUTStudentsBundle:Student:addStudent
    methods:  [POST]

delete_student:
    path:     /students/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Student:deleteStudent
    methods:  [DELETE]
    requirements:
        id: \d+

delete_students:
    path:     /students
    defaults:
        _controller: FormerDUTStudentsBundle:Student:deleteStudents
    methods:  [DELETE]
    requirements:
        id: \d+

edit_student:
    path:     /students/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Student:editStudent
    methods:  [PUT]
    requirements:
        id: \d+

add_formations_to_student:
    path:     /students/{id}/formations
    defaults:
        _controller: FormerDUTStudentsBundle:Student:addFormationsToStudent
    methods:  [POST]
    requirements:
        id: \d+

self:
    path:     /self
    defaults:
        _controller: FormerDUTStudentsBundle:Student:self
        _format: json
    methods:  [GET]


test:
    path:     /test/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Student:test
    methods:  [POST]

################################ Route to securities methods ######################################

check_if_logged:
    path:     /isLogged
    defaults:
        _controller: FormerDUTStudentsBundle:Login:isLogged
        _format: json
    methods:  [GET]

login:
    path: /login
    defaults:
        _controller: FormerDUTStudentsBundle:Login:login

login_check:
    path: /login_check

logout:
    path: /logout

################################ Route to formations methods ######################################

formations:
    path:     /formations
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:getFormations
        _format: json
    methods:  [GET]

formation:
    path:     /formations/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:getFormation
    methods:  [GET]
    requirements:
        id: \d+

add_formation:
    path:     /formations
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:addFormation
    methods:  [POST]

delete_formation:
    path:     /formations/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:deleteFormation
    methods:  [DELETE]
    requirements:
        id: \d+

delete_formations:
    path:     /formations
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:deleteFormations
    methods:  [DELETE]
    requirements:
        id: \d+

edit_formation:
    path:     /formations/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:Formation:editFormation
    methods:  [PUT]
    requirements:
        id: \d+

################################ Route to credentials methods ######################################

edit_user:
    path:     /user/{id}
    defaults:
        _controller: FormerDUTStudentsBundle:User:editUser
    methods:  [PUT]
    requirements:
        id: \d+

################################ Route to mails methods ######################################

send_mails:
    path:     /mail
    defaults:
        _controller: FormerDUTStudentsBundle:Mail:sendMail
    methods:  [POST]