services:
#    former_dut_students.example:
#        class: FormerDUTStudentsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    former_dut_students.credentials:
          class: FormerDUTStudentsBundle\Model\Credentials
          arguments:
              - "@doctrine.orm.entity_manager"

    former_dut_students.user:
          class: FormerDUTStudentsBundle\Model\User
          arguments:
              - "@former_dut_students.credentials"

    former_dut_students.mail:
              class: FormerDUTStudentsBundle\Model\Mail
              arguments:
                  - "@mailer"
                  - '%mailer_user%'

