<?php

namespace FormerDUTStudentsBundle\Repository;

/**
 * StudentFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
